compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /workdir/accelerate_config/ds_config.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 1
use_cpu: false
